sudo: false
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - build-essential
      - check
      - dh-autoreconf
      - hardening-wrapper
      - libglib2.0-dev
      - ruby
      - ruby-dev
install:
  - gem install fpm
  - autoreconf -i
script:
  - ./script/build.sh
after_failure:
  - cat config.log
  - cat test/*.log
